// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Chassis
    {
        [DataMember(Name = "ArmorPointsAllowed")]
        public int ArmorPointsAllowed;

        public Chassis(int ArmorPointsAllowed)
        {
            this.ArmorPointsAllowed = ArmorPointsAllowed;
        }

        public Chassis()
        {
        }
    }
}
