// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class Tank
    {
        [DataMember(Name = "OwningPlayer")]
        public SpacetimeDB.Identity OwningPlayer;
        [DataMember(Name = "ChassisId")]
        public int ChassisId;
        [DataMember(Name = "TurrentId")]
        public int TurrentId;
        [DataMember(Name = "EngineId")]
        public int EngineId;
        [DataMember(Name = "RemainingArmorPoints")]
        public int RemainingArmorPoints;
        [DataMember(Name = "Created")]
        public SpacetimeDB.Timestamp Created;
        [DataMember(Name = "LastUpdated")]
        public SpacetimeDB.Timestamp LastUpdated;

        public Tank(
            SpacetimeDB.Identity OwningPlayer,
            int ChassisId,
            int TurrentId,
            int EngineId,
            int RemainingArmorPoints,
            SpacetimeDB.Timestamp Created,
            SpacetimeDB.Timestamp LastUpdated
        )
        {
            this.OwningPlayer = OwningPlayer;
            this.ChassisId = ChassisId;
            this.TurrentId = TurrentId;
            this.EngineId = EngineId;
            this.RemainingArmorPoints = RemainingArmorPoints;
            this.Created = Created;
            this.LastUpdated = LastUpdated;
        }

        public Tank()
        {
        }
    }
}
