// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class User
    {
        [DataMember(Name = "Identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "Name")]
        public string? Name;
        [DataMember(Name = "Online")]
        public bool Online;
        [DataMember(Name = "LastSeen")]
        public SpacetimeDB.Timestamp LastSeen;

        public User(
            SpacetimeDB.Identity Identity,
            string? Name,
            bool Online,
            SpacetimeDB.Timestamp LastSeen
        )
        {
            this.Identity = Identity;
            this.Name = Name;
            this.Online = Online;
            this.LastSeen = LastSeen;
        }

        public User()
        {
        }
    }
}
